# Generated by Django 5.1.6 on 2025-06-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('open', 'Опубликован'), ('review', 'На рассмотрении')], default='draft', max_length=20),
        ),
    ]
