# Generated by Django 5.1.6 on 2025-06-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_alter_offers_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='offer_type',
            field=models.CharField(choices=[('toir', 'ТОИР'), ('other', 'Прочее')], default='other', max_length=20),
        ),
    ]
