# Generated by Django 5.1.6 on 2025-05-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('semester', models.CharField(choices=[('spring', 'Весенний'), ('winter', 'Зимний')], max_length=10)),
            ],
            options={
                'ordering': ['-year', 'semester'],
                'unique_together': {('year', 'semester')},
            },
        ),
    ]
