# Generated by Django 5.1.6 on 2025-04-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='type',
            field=models.CharField(choices=[('programming', 'Программирование'), ('design', 'Дизайн')], default='programming', max_length=50, verbose_name='Раздел'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
    ]
