# Generated by Django 5.1.6 on 2025-05-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_technology_type_alter_technology_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='type',
            field=models.CharField(choices=[('programming', 'Программирование'), ('design', 'Дизайн')], max_length=50, verbose_name='Раздел'),
        ),
    ]
