# Generated by Django 5.1.6 on 2025-04-16 19:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_technology_type_alter_technology_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='users',
            field=models.ManyToManyField(related_name='technologies', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи'),
        ),
    ]
