# Generated by Django 5.1.6 on 2025-07-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_semester_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='universitygroup',
            name='institute',
            field=models.CharField(choices=[('HSDT', 'ВШЦТ'), ('IPTI', 'ИПТИ'), ('STROIN', 'СТРОИН'), ('ARHID', 'АРХИД')], default='HSDT', max_length=10, verbose_name='Институт'),
        ),
        migrations.AlterUniqueTogether(
            name='universitygroup',
            unique_together={('name', 'institute')},
        ),
    ]
