# Generated by Django 5.1.6 on 2025-02-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('technologies', '0002_alter_technology_options'),
        ('users', '0003_userprofile_technologies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('max_members', models.IntegerField(default=5)),
                ('privacy', models.CharField(choices=[('open', 'Открытая'), ('invite', 'По приглашению')], default='open', max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('members', models.ManyToManyField(related_name='teams', to='users.userprofile')),
                ('technologies', models.ManyToManyField(related_name='teams', to='technologies.technology')),
            ],
        ),
    ]
