# Generated by Django 5.1.6 on 2025-04-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_teamjoinrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamjoinrequest',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
