# Generated by Django 5.1.6 on 2025-04-16 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_teamjoinrequest_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='status',
            field=models.CharField(choices=[('open', 'Открыта'), ('private', 'Приватная'), ('in_progress', 'В работе')], default='open', max_length=20),
        ),
    ]
