# Generated by Django 5.1.6 on 2025-07-13 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_idea_team_idea_teams_working_on_alter_idea_status_and_more'),
        ('teams', '0003_team_ideas_team_projects'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='status',
            field=models.CharField(choices=[('open', 'Открыта'), ('private', 'Приватная'), ('in_progress', 'В работе'), ('over', 'Распалась')], default='open', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['active', 'private'])), fields=('owner',), name='unique_active_team_per_owner'),
        ),
    ]
