# Generated by Django 5.1.6 on 2025-07-13 12:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_idea_team_idea_teams_working_on_alter_idea_status_and_more'),
        ('teams', '0004_alter_team_owner_alter_team_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='team',
            name='unique_active_team_per_owner',
        ),
        migrations.AddField(
            model_name='team',
            name='disbanded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['active', 'private', 'in_progress'])), fields=('owner',), name='unique_active_team_per_owner'),
        ),
    ]
