# Generated by Django 5.1.6 on 2025-02-18 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='initiator',
        ),
        migrations.RemoveField(
            model_name='project',
            name='initiator',
        ),
        migrations.RemoveField(
            model_name='project',
            name='owner',
        ),
    ]
