# Generated by Django 5.1.6 on 2025-03-25 17:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='experts_voted',
            field=models.ManyToManyField(blank=True, related_name='voted_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
