# Generated by Django 5.1.6 on 2025-03-25 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='client',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='experts',
            new_name='experts_voted',
        ),
    ]
