# Generated by Django 5.1.6 on 2025-03-25 14:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_client_project_customer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='experts_voted',
        ),
        migrations.AddField(
            model_name='project',
            name='applicants',
            field=models.ManyToManyField(blank=True, related_name='applied_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='is_hiring',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('open', 'Открыт'), ('customer_found', 'Заказчик найден'), ('in_progress', 'В работе'), ('completed', 'Завершён'), ('cancelled', 'Отменён')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
