# Generated by Django 5.1.6 on 2025-03-26 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_experts_voted'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='max_members',
            field=models.IntegerField(default=5),
        ),
    ]
