# Generated by Django 5.1.6 on 2025-04-16 17:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_project_skills_required_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='applicants',
            field=models.ManyToManyField(blank=True, related_name='applied_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='experts_voted',
            field=models.ManyToManyField(blank=True, related_name='voted_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='workers',
            field=models.ManyToManyField(blank=True, related_name='working_on_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
