# Generated by Django 5.1.6 on 2025-05-27 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='duration',
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('semester', models.CharField(choices=[('winter', 'Зимний семестр'), ('spring', 'Весенний семестр')], max_length=10)),
            ],
            options={
                'unique_together': {('year', 'semester')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.semester'),
        ),
    ]
