# Generated by Django 5.1.6 on 2025-05-15 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projectparticipant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectparticipant',
            options={'verbose_name': 'Участник проекта', 'verbose_name_plural': 'Участники проекта'},
        ),
        migrations.RemoveField(
            model_name='projectparticipant',
            name='team',
        ),
        migrations.AlterField(
            model_name='projectparticipant',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
