# Generated by Django 5.1.6 on 2025-04-16 19:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_votes_to_approve_idea'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='skills_required',
        ),
        migrations.AddField(
            model_name='idea',
            name='technologies',
            field=models.ManyToManyField(blank=True, related_name='ideas_with', to=settings.AUTH_USER_MODEL),
        ),
    ]
