# Generated by Django 5.1.6 on 2025-05-27 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_semester'),
        ('projects', '0004_remove_project_experts_voted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.semester'),
        ),
        migrations.DeleteModel(
            name='Semester',
        ),
    ]
