# Generated by Django 5.1.6 on 2025-04-16 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_idea_skills_required_idea_technologies'),
        ('teams', '0004_alter_team_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='selected_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='teams.team'),
        ),
        migrations.CreateModel(
            name='TeamResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_responses', to='projects.project')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='teams.team')),
            ],
            options={
                'unique_together': {('project', 'team')},
            },
        ),
    ]
