# Generated by Django 5.1.6 on 2025-02-18 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_idea_likes_project_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='members',
        ),
    ]
