# Generated by Django 5.1.6 on 2025-05-16 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_teams_alter_project_workers'),
        ('projects', '0006_projectparticipantrating_delete_projectparticipant'),
    ]

    operations = [
    ]
