# Generated by Django 5.1.6 on 2025-05-29 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_status_projectmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='institutes',
            field=models.ManyToManyField(related_name='projects', to='projects.institute'),
        ),
    ]
