# Generated by Django 5.1.6 on 2025-05-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_institute_project_institutes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='institutes',
        ),
        migrations.AddField(
            model_name='project',
            name='institutes',
            field=models.CharField(blank=True, default='[]', max_length=255),
        ),
    ]
