# Generated by Django 5.1.6 on 2025-05-16 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_merge_20250516_1616'),
        ('teams', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='projects', to='teams.team'),
        ),
    ]
