# Generated by Django 5.1.6 on 2025-06-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_remove_project_institutes_project_institutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('review', 'На рассмотрении'), ('open', 'В поиске'), ('in_progress', 'В работе'), ('under_revision', 'На доработке'), ('done', 'Сделан'), ('new', 'Новый')], default='draft', max_length=20),
        ),
    ]
