# Generated by Django 5.1.6 on 2025-06-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('review', 'На рассмотрении'), ('open', 'В поиске'), ('in_progress', 'В работе'), ('under_revision', 'На доработке'), ('done', 'Сделан'), ('new', 'Новый'), ('under_revision_on_admin', 'На доработке дирекции')], default='draft', max_length=25),
        ),
    ]
