# Generated by Django 5.1.6 on 2025-06-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmessage',
            name='sender_role',
            field=models.CharField(blank=True, choices=[('expert', 'Expert'), ('admin', 'Admin'), ('user', 'User')], max_length=20, null=True),
        ),
    ]
