# Generated by Django 5.1.6 on 2025-06-23 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_projectmessage_sender_role'),
        ('teams', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ideas_team', to='teams.team'),
        ),
        migrations.AddField(
            model_name='idea',
            name='teams_working_on',
            field=models.ManyToManyField(blank=True, related_name='ideas_working_on', to='teams.team'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('open', 'Опубликован'), ('private', 'Приватная'), ('under_review', 'На согласовании')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='projects_team', to='teams.team'),
        ),
    ]
