# Generated by Django 5.1.6 on 2025-02-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('group', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('team', models.CharField(blank=True, max_length=100, null=True)),
                ('total_rating', models.FloatField(default=0)),
                ('rated_by_amount', models.FloatField(default=0)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('skills', models.ManyToManyField(related_name='users_with_skill', to='core.technology')),
            ],
        ),
    ]
