# Generated by Django 5.1.6 on 2025-06-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('ST', 'Student'), ('CU', 'Customer'), ('EX', 'Expert'), ('AD', 'Admin')], default='ST', max_length=2),
        ),
    ]
