# Generated by Django 5.1.6 on 2025-02-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
