# Generated by Django 5.1.6 on 2025-02-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='team',
        ),
        migrations.AlterField(
            model_name='account',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, related_name='users_with_skill', to='core.technology'),
        ),
    ]
