# Generated by Django 5.1.6 on 2025-02-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technologies', '0002_alter_technology_options'),
        ('users', '0002_rename_customuser_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='technologies',
            field=models.ManyToManyField(blank=True, to='technologies.technology'),
        ),
    ]
