# Generated by Django 5.1.6 on 2025-02-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('users', '0002_remove_account_team_alter_account_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='users_with_skill', to='core.technology'),
        ),
    ]
