# Generated by Django 5.1.6 on 2025-02-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_account_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='group',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
