# Generated by Django 5.1.6 on 2025-02-18 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_account_skills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='date_joined',
            new_name='created_at',
        ),
    ]
