# Generated by Django 5.1.6 on 2025-02-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_date_joined_account_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='password',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
