# Generated by Django 5.1.6 on 2025-03-21 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_delete_outstandingtoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='group',
            new_name='university_group',
        ),
        migrations.AddField(
            model_name='account',
            name='company_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('ST', 'Student'), ('CU', 'Customer'), ('EX', 'Expert')], default='ST', max_length=2),
        ),
    ]
