# Generated by Django 5.1.6 on 2025-05-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('team_join_request_sent', 'Заявка в команду отправлена'), ('team_join_request_accepted', 'Заявка в команду принята'), ('added_to_team', 'Добавление в команду'), ('project_join_request_sent', 'Заявка в проект отправлена'), ('project_join_request_accepted', 'Заявка в проект принята'), ('system', 'Системное уведомление')], default='info', max_length=50)),
                ('message', models.TextField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
