# Generated by Django 5.1.6 on 2025-06-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('team_join_request_sent', 'Заявка в команду отправлена'), ('team_join_request_accepted', 'Заявка в команду принята'), ('added_to_team', 'Добавление в команду'), ('project_join_request_sent', 'Заявка в проект отправлена'), ('project_join_request_accepted', 'Заявка в проект принята'), ('system', 'Системное уведомление'), ('project_on_under_revision', 'Проект отправлен на доработку')], default='info', max_length=50),
        ),
    ]
