# Generated by Django 5.1.6 on 2025-05-08 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0001_initial'),
        ('teams', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='board',
            name='name',
        ),
        migrations.AddField(
            model_name='board',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='teams.team'),
            preserve_default=False,
        ),
    ]
