# Generated by Django 5.1.6 on 2025-05-28 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0003_initial'),
        ('projects', '0006_alter_project_status_projectmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='project',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='projects.project'),
            preserve_default=False,
        ),
    ]
