# Generated by Django 5.1.6 on 2025-05-28 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0004_board_project'),
        ('projects', '0006_alter_project_status_projectmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
    ]
