# Generated by Django 5.1.6 on 2025-07-01 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0005_alter_board_project'),
        ('projects', '0012_idea_team_idea_teams_working_on_alter_idea_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='idea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.idea'),
        ),
    ]
